github.com:
    users:
        Rayaa144:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Rayaa144
